In [5]:
x = [1,2,3]
y = [2,3,4]
ans = []
for a, b in zip(x, y):
    v = a + b
    ans.append(v)
print(ans) 

[3, 5, 7]


In [6]:
x = [1,3], [2,4]
y = [2,4], [3,5]

number processing library for python - numpy

array : it is a list of homogenous elements

In [2]:
import numpy as np



In [14]:
x = np.array([[1,3], [2,4]])
y = np.array([[2,4], [3,5]])
print(x,'+',y, '=', x+y)
print(x,'-',y, '=', x-y)
print(x,'*',y, '=', x*y)
print(x,'/',y, '=', x/y)

[[1 3]
 [2 4]] + [[2 4]
 [3 5]] = [[3 7]
 [5 9]]
[[1 3]
 [2 4]] - [[2 4]
 [3 5]] = [[-1 -1]
 [-1 -1]]
[[1 3]
 [2 4]] * [[2 4]
 [3 5]] = [[ 2 12]
 [ 6 20]]
[[1 3]
 [2 4]] / [[2 4]
 [3 5]] = [[0.5        0.75      ]
 [0.66666667 0.8       ]]


In [ ]:
x = np.array([1,2,3])
y = np.array([2,3,4])
print(x,'+',y, '=', x+y)
print(x,'-',y, '=', x-y)
print(x,'*',y, '=', x*y)
print(x,'/',y, '=', x/y)

Matrices are:

- 1D array
- 2D array
- 3D array
- 4D array
- nD array

In [19]:
x = np.array([1,2,3])
print(x, type(x), x.shape, x.ndim)
x2 = np.array([[1,2],[3,4]])
print(x2, type(x2), x2.shape, x2.ndim)

[1 2 3] <class 'numpy.ndarray'> (3,) 1
[[1 2]
 [3 4]] <class 'numpy.ndarray'> (2, 2) 2


In [17]:
x3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(x3, x3.shape, x3.ndim, x3.size)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2) 3 8


In [18]:
# 6 * 6 matrix 

Matrix generation in numpy
- array() # basic
- linspace() # range of values with equal gap
- logspace() # range of values with equal gap in lg scale
- zeros() # array with all zeros
- ones() # array with all one
- eye() # identity matrix
- diag() # diagonal matrix
- random.rand() # random matrix of given shape 0 to 1
- random.randn() # random matrix of shape from -1 to 1
- random.randomint() # random matrix of given shape from given range

In [22]:
# arange() function
x = np.arange(10)
print(x)
x1 = np.arange(-10,11,0.5)
print(x1)
x2 = np.arange(-np.pi, np.pi, 2)
x3 = np.arange(1,15,2)
print(x3)

[0 1 2 3 4 5 6 7 8 9]
[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5  10.   10.5]
[ 1  3  5  7  9 11 13]


In [23]:
x = np.linspace(0, 10, 10) # 5 number of elements
print(x)
x = np.linspace(0,500,100)
print(x)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[  0.           5.05050505  10.1010101   15.15151515  20.2020202
  25.25252525  30.3030303   35.35353535  40.4040404   45.45454545
  50.50505051  55.55555556  60.60606061  65.65656566  70.70707071
  75.75757576  80.80808081  85.85858586  90.90909091  95.95959596
 101.01010101 106.06060606 111.11111111 116.16161616 121.21212121
 126.26262626 131.31313131 136.36363636 141.41414141 146.46464646
 151.51515152 156.56565657 161.61616162 166.66666667 171.71717172
 176.76767677 181.81818182 186.86868687 191.91919192 196.96969697
 202.02020202 207.07070707 212.12121212 217.17171717 222.22222222
 227.27272727 232.32323232 237.37373737 242.42424242 247.47474747
 252.52525253 257.57575758 262.62626263 267.67676768 272.72727273
 277.77777778 282.82828283 287.87878788 292.92929293 297.97979798
 303.03030303 308.08080808 313.13131313 318.18181818 323.23232323
 328.28282828 333.33

In [24]:
z = np.zeros(10)
print(z)
z1 = np.zeros((2,3))
print(z1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [28]:
o = np.ones((4,5))
print(o)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
e = np.eye(5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [31]:
e = np.eye(5, dtype=int)
print(e)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [36]:
np.random.randn(3,3)

array([[-0.47637604,  0.72089822,  0.28461087],
       [ 2.38846412,  1.29059277,  0.24280052],
       [-1.23177808, -0.02581662,  0.62305931]])

In [37]:
np.random.randint(11, 15, (5,5))

array([[12, 11, 11, 14, 12],
       [11, 13, 12, 13, 12],
       [13, 13, 11, 13, 14],
       [12, 14, 11, 11, 12],
       [11, 13, 14, 14, 13]])

Matrix operations

In [16]:
x = np.random.randint(1,100, (4,4))
print(x)

[[71 79 62 40]
 [89 70  7 53]
 [36 30 51 80]
 [65 12 71 77]]


In [17]:
# sum of all values
total = x.sum() # or np.sum(x)
print(total)
# sum of each column
col_total = x.sum(axis=0) # or np.sum(x, axis =0)
print(col_total)
col_total = x.sum(axis=1) # or np.sum(x, axis =0)
print(col_total)

893
[261 191 191 250]
[252 219 197 225]


In [18]:
total = x.mean() # or np.sum(x)
print(total)
print(np.median(x))
print(np.(x)) #


SyntaxError: invalid syntax (2326274658.py, line 4)

In [14]:
np.sin(90)

0.8939966636005579

In [19]:
x.prod() # product of all values

-2009677824

In [20]:
np.linalg.det(x)

16383898.000000045

In [21]:
y = np.random.randint(0,10, (5,5))
print(y)
print('checking if there is no zeroes in the matrix')
print(np.all(y)) # or y.all

[[4 1 1 6 9]
 [4 7 7 6 1]
 [2 8 1 6 7]
 [2 1 1 6 1]
 [1 1 8 2 0]]
checking if there is no zeroes in the matrix
False


In [23]:
z = np.random.choice([0,1,0,0], (5,5))
print(z)
print('checking if there is any +/- value in the matrix')
print(z.any())

[[0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [1 0 0 0 0]]
checking if there is any +/- value in the matrix
True


In [25]:
x = np.random.randint(1,10, (4,4))
print('shape', x.shape)
print('x')
print(x)
x = x.T # transpose
print('x transposed')
print(x)
x = x.flatten() # Flatten or ravel
print('x flattened')
print(x)

shape (4, 4)
x
[[4 9 8 5]
 [4 2 7 8]
 [3 5 7 3]
 [4 9 1 3]]
x transposed
[[4 4 3 4]
 [9 2 5 9]
 [8 7 7 1]
 [5 8 3 3]]
x flattened
[4 4 3 4 9 2 5 9 8 7 7 1 5 8 3 3]


In [31]:
x.reshape(1,16)




array([[4, 4, 3, 4, 9, 2, 5, 9, 8, 7, 7, 1, 5, 8, 3, 3]])

In [32]:
x.reshape(1,1,1,1,1,16)

array([[[[[[4, 4, 3, 4, 9, 2, 5, 9, 8, 7, 7, 1, 5, 8, 3, 3]]]]]])

In [33]:
x.reshape(8,2)

array([[4, 4],
       [3, 4],
       [9, 2],
       [5, 9],
       [8, 7],
       [7, 1],
       [5, 8],
       [3, 3]])

In [34]:
x.reshape(4,4)

array([[4, 4, 3, 4],
       [9, 2, 5, 9],
       [8, 7, 7, 1],
       [5, 8, 3, 3]])

# slicing and filtering

In [35]:
print(x.ndim,'dimension')
print(x.size,'elements')
print(x)

1 dimension
16 elements
[4 4 3 4 9 2 5 9 8 7 7 1 5 8 3 3]


In [36]:
# slicing for 2d object
# arr[row, col]
y = np.random.randint(1,10, (6,6))
print(x.ndim,'dimension')
print(x.size,'elements')
print(y)
print('first row', y[0])
print('last row', y[-1])
print('first 3 rows\n', y[:3])
print('last 2 row', y[-2:])





1 dimension
16 elements
[[2 3 6 4 6 4]
 [5 9 9 6 8 6]
 [3 6 8 6 3 2]
 [4 4 5 6 4 6]
 [2 4 2 5 8 3]
 [7 5 3 4 7 3]]
first row [2 3 6 4 6 4]
last row [7 5 3 4 7 3]
first 3 rows
 [[2 3 6 4 6 4]
 [5 9 9 6 8 6]
 [3 6 8 6 3 2]]
last 2 row [[2 4 2 5 8 3]
 [7 5 3 4 7 3]]


In [42]:
y = np.random.randint(1,10, (6,6))
print(y)
print('first column\n', y[:,0])
print('last column\n', y[:,-1])
print('first 3 column\n', y[:,:3])
print('first column\n', y[:,-2:])

[[5 5 3 2 4 8]
 [5 8 4 2 7 9]
 [4 3 2 7 1 7]
 [9 5 7 5 9 4]
 [9 8 4 9 6 8]
 [6 8 8 3 1 2]]
first column
 [5 5 4 9 9 6]
last column
 [8 9 7 4 8 2]
first 3 column
 [[5 5 3]
 [5 8 4]
 [4 3 2]
 [9 5 7]
 [9 8 4]
 [6 8 8]]
first column
 [[4 8]
 [7 9]
 [1 7]
 [9 4]
 [6 8]
 [1 2]]


In [43]:
y > 5 # boolean filter

array([[False, False, False, False, False,  True],
       [False,  True, False, False,  True,  True],
       [False, False, False,  True, False,  True],
       [ True, False,  True, False,  True, False],
       [ True,  True, False,  True,  True,  True],
       [ True,  True,  True, False, False, False]])

In [44]:
y[y > 5]

array([8, 8, 7, 9, 7, 7, 9, 7, 9, 9, 8, 9, 6, 8, 6, 8, 8])

In [45]:
y[y < 3]

array([2, 2, 2, 1, 1, 2])

In [47]:
y[(y >= 3) & (y <= 5)] # 3 <= y <= 5

array([5, 5, 3, 4, 5, 4, 4, 3, 5, 5, 4, 4, 3])

# Graph library matplotlib

In [48]:
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.sin(x)
plt.plot(x,y)
plt.show()

ModuleNotFoundError: No module named 'matplotlib'