In [1]:
import numpy as np

In [6]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
x = np.ones(10)
print(x)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
x = np.random.randint(0,8,(3,3))
print(x)

[[4 7 3]
 [7 3 2]
 [0 4 0]]


In [13]:
x = np.array([3,5,6,7,8,2,9])
y = np.flip(x)
print('Original array', x)
print('Reversed array', y)

Original array [3 5 6 7 8 2 9]
Reversed array [9 2 8 7 6 5 3]


In [15]:
import numpy as np

# Create an array
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extract odd numbers
y = x[x % 2 != 0]

print("Original Array:", x)
print("Odd Numbers:", y)


Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Odd Numbers: [1 3 5 7 9]


In [32]:
x = np.random.randint(1,15,(8))
print(x)

[ 9  5  9  7  5  5 10 11]


In [33]:
np.sum(x)


61

In [34]:
np.mean(x)

7.625

In [35]:
np.std(x)

2.2878756522153907